version: "3.9"
services:
  dev:
    build: 
      context: ./dev
    ports:
      - ${CONTAINER_PORT}:80
    tty: true
    volumes:
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
      - ${HOME}/.gitconfig:/root/.gitconfig
    restart: unless-stopped
    networks:
      - my_shared_network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  my_shared_network:
    external: true
