version: "3.9"
services:
  dev:
    build: 
      context: ./dev
      args:
        GITCONFIG_EMAIL: ${GITCONFIG_EMAIL}
        GITCONFIG_NAME: ${GITCONFIG_NAME}
        APP_NAME: ${APP_NAME}
    ports:
      - 6379:80
    tty: true
    restart: unless-stopped